// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "Common.cginc"

RWStructuredBuffer<int> array;
RWTexture3D<float4> tex;
int w, h, d;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= w || id.y >= h || id.z >= d)
        return;
    int idx = (w * h) * id.z + w * id.y + id.x;
    tex[id.xyz] = float4(
        1, 1, 1,
        (float)((array[idx / 2] >> ((idx % 2) * 16)) & 0xFFFF) / 65536.0
    );
}
